-- PARA QUE SERVE DISTINCT 
-- SERVE PARA REMOVER LINHAS DUPLICADAS E MOSTRAR APENAS LINHAS DISTINTAS 
-- MUITO USADO NA ETAPA  DE EXPLORAÇÃO DAS BASES 



-- SINTAXE 

select distinct coluna_1, coluna_2, coluna_3
from schema_1, tabela_1


-- (EXEMPLO 1) SELEÇÃO  DE UMA COLUNA SEM DISTINCT 
-- LISTE AS MARCAS DE CARRO QUE COSTEM NA TABELA PRODUCTS 

select brand 
from sales.products  --333 linhas 



-- (EXEMPLO 2) SELEÇÃO  DE UMA COLUNA COM DISTINCT 
-- LISTE  AS MARCAS DE CARRO DISTINTAS QUE CONTAM NA TABELA PRODUCTS 

select distinct brand
from sales.products -- 40 linhas 


-- (EXEMPLO 3) SELEÇÃO  DE MAIS DE UMA COLUNA COM DISTINCT 
-- LISTE AS MARCAS  E ANOS DE  MODELO DISTINTAS QUE CONSTAM NA TABELA PRODUCTS

SELECT distinct brand, model_year
from sales.products 