--FUNÇÃO DE AGREGAÇÃO PARA QUE SERVE ?
-- SERVEM PARA EXECUTAR OPERAÇÕES ARITMÉTICAS NOS REGISTROS DE UMA COLUNA 



--TIPOS DE FUNÇÕES AGREGADAS 
-- COUNT ()
-- SUM ()
-- MIN()
-- MAX()
-- AVG()

--EXEMPLOS 

--COUNT ()


--(EXEMPLO 1) CONTAGEM DE TODAS AS DE LINHA DE UMA TABELA 
--CONTE TODAS AS VISITAS REALIZADAS AO SITE DA EMPRESA FICTÍCIA 

SELECT COUNT(*)
FROM SALES.FUNNEL


--CONTAGEM DE LINHAS DE UMA COLUNA 
--CONTE TODOS OS PAGAMENTOS REGISTRADOS NA TABELA SALES.FUNNEL

SELECT *
FROM SALES.FUNNEL
LIMIT 10

SELECT COUNT(paid_date)
from sales.funnel


--CONTAGEM DISTINTA DE UMA COLUNA 
--CONTE TODOS OS PRODUTOS DISTINTOS VISITANDOS EM JAN/21

SELECT COUNT(DISTINCT PRODUCT_ID)
FROM SALES.FUNNEL
WHERE VISIT_PAGE_DATE  BETWEEN '2021-01-01' AND '2021-01-31'



--(EXEMPLO 4) CALCULE O PREÇO MINIMO, MAXIMO  E MEDIO DOS PRODUTOS 	DA TABELA PRODUCTS
SELECT MIN(PRICE), MAX(PRICE), AVG(PRICE)
FROM SALES.PRODUCTS


--(EXEMPLO 5) INFORME QUAL É O VEICULO MAIS CARO DA TABELA PRODUCTS 
SELECT MAX(PRICE) FROM SALES.PRODUCTS
--BUT, CADE AS OUTRAS INFORMAÇOES DESSE PRODUTO ? HUMMM 

SELECT *
FROM SALES.PRODUCTS 
WHERE PRICE = (SELECT MAX(PRICE) FROM SALES.PRODUCTS)
