--AGRUPAR POR PARA QUE SERVEEE? VAMOS LA?
--SERVE PARA AGRUPAR REGISTROS SEMELHANTES DE UMA COLUNA 
--NORMALMENTE UTILIZANDO EM CONJUNTO COM AS FUNCOES DE AGREGACAO 


--EXEMPLOSSSSSS

--(EXEMPLO 1) CONTAMGEM AGRUPADA DE UMA COLUNA 
--CALCULE O N DE CLIENTES DA TABELA CUSTOMERS POR ESTADO 

SELECT STATE, COUNT(*) AS contagem
FROM SALES.CUSTOMERS
GROUP BY STATE
order by contagem  desc



--(EXEMPLO 2) CONTAGEM AGRUPADA DE VARIAS COLUNAS 
--CALCULE O N DE CLIENTES POR ESTADO E STATUS PROFISSIONAL 

SELECT STATE, PROFESSIONAL_STATUS, COUNT(*) AS contagem
FROM SALES.CUSTOMERS
GROUP BY STATE, PROFESSIONAL_STATUS
order by STATE, contagem  desc


--(EXEMPLO 3) SELECAO DE VALORES DISTINTOS 
--SELECIONE OS ESTADOS DISTINTOS NA TABELA CUSTOMERS UTILIZANDO O GROUP BY

SELECT DISTINCT STATE
FROM SALES.CUSTOMERS

SELECT STATE 
FROM SALES.CUSTOMERS
GROUP BY STATE


