-- PARA QUE SERVE HAVING 
--SERVE PARA FILTRAR LINAHS DE SELEÇÃO POR UMA COLUNA AGRUPADA 


--(EXEMPLOS)


--(EXEMPLO 1) SELEÇÃO COM FILTRO NO HAVING 
--CALCULE O N DE CLIENTES POR ESTADO FILTRANDO APENAS ESTADOS ACIMA DE 100 CLIENTES 

SELECT
	STATE,                          --PENSEI EM COLOCAR WHERE, MAS OOPS, NAO DA.
	COUNT(*)
FROM SALES.CUSTOMERS
--WHERE COUNT(*) > 100
GROUP BY STATE
HAVING COUNT(*) > 100
