--TIPOS DE JOIN 
--VAMOS LA ? HEHE

--(EXEMPLO 1) UTILIZE O LEFT JOIN PARA FAZER JOIN ENTRE AS TABELAS 
--TEMP_TABLES.TABELA_1 E TEMP_TABLES.TABELA_2

SELECT * FROM TEMP_TABLES.TABELA_1
SELECT * FROM TEMP_TABLES.TABELA_2

SELECT T1.CPF, T1.NAME, T2.STATE
FROM TEMP_TABLES.TABELA_1 AS T1 
LEFT JOIN TEMP_TABLES.TABELA_2 AS T2
	ON T1.CPF = T2.CPF


--(EXEMPLO 2) UTILIZE O INNER JOIN  PARA FAZER JOIN ENTRE AS TABELAS 
--TEMP_TABLES.TABELA_1 E TEMP_TABLES.TABELA_2


SELECT T1.CPF, T1.NAME, T2.STATE
FROM TEMP_TABLES.TABELA_1 AS T1 
INNER JOIN TEMP_TABLES.TABELA_2 AS T2
	ON T1.CPF = T2.CPF

--(EXEMPLO 3) UTILIZE O RIGHT JOIN  PARA FAZER JOIN ENTRE AS TABELAS 
--TEMP_TABLES.TABELA_1 E TEMP_TABLES.TABELA_2

SELECT T2.CPF, T1.NAME, T2.STATE
FROM TEMP_TABLES.TABELA_1 AS T1 
RIGHT JOIN TEMP_TABLES.TABELA_2 AS T2
	ON T1.CPF = T2.CPF


--(EXEMPLO 4) UTILIZE O FULL JOIN  PARA FAZER JOIN ENTRE AS TABELAS 
--TEMP_TABLES.TABELA_1 E TEMP_TABLES.TABELA_2

SELECT T2.CPF, T1.NAME, T2.STATE
FROM TEMP_TABLES.TABELA_1 AS T1 
FULL JOIN TEMP_TABLES.TABELA_2 AS T2
	ON T1.CPF = T2.CPF
