-- PARA QUE SERVE LIMIT 
-- SERVE PARA LIMITARO N DE LINHAS DA CONSULTA 
-- MUITO UTILIZADO NA ETAPA DE EXPLORACAO DE DADOS 


--SINTAXE 

SELECT COLUNA_1, COLUNA_2, COLUNA_3
FROM SCHEMA_1.TABELA_1
WHERE CONDICAO_X=TRUE
ORDER BY COLUNA_1
LIMIT N


--(EXEMPLO 1) SELECAO DAS N PRIMEIRAS LINHAS USANDO LIMIT 
--LISTE AS 10 PRIMEIRAS LINHAS DA TABELA FUNNEL 

SELECT * 
FROM sales.funnel
limit 10 


--(EXEMPLO 2) SELECAO DAS N PRIMEIRAS LINHAS USANDO LIMIT E ORDER BY
--LISTE 10 PRODUTOS  MAIS CAROS A TABELA PRODUCTS 

SELECT *
from sales.products
order by price desc
limit 10 