--PARA QUE SERVE OS OPERADORES DE COMPARACAO 
-- SERVEM PARA COMPARAR DOIS VALORES RETORNANDO TRUE OU FALSE 
--MUITO UTILIZADO EM CONJUNTO COM A FUNCAO WHERE PARA FILTRAR LINHAS DE UMA SELECAO 

-- TIPOS 
-- =
-- >
-- <
-- >=
-- <>

--(EXEMPLO 1) USO DE OPERADORES COM FLAG 
-- CRIE UMA COLUNA QUE RETORNE TRUE SEMPRE QUE UM CLIENTE FOR UM PROFISSONAL CLT 

SELECT
	customer_id,
	first_name,
	professional_status,
	(professional_status = 'clt') as cliente_clt
from sales.customers	


