--PARA QUE SERVE OS OPERADOR LOGICOS ?
--USADOS PARA UNIR EXPRESSOES SIMPLES EM UMA COMPOSTA 


-- TIPOS 
-- AND 
-- OR
-- NOT
-- BETWEEN
-- IN 
-- LIKE
-- IKIKE
-- IS NULL

--(EXEMPLO 1) USO DE COMENDO BETWEEN
--SELECIONE VEICULOS QUE CUSTAM ENTRE 100K E 200K NA TABELA PRODUCTS

SELECT  *
FROM SALES.PRODUCTS 
WHERE PRICE >= 100000 AND PRICE <= 200000

SELECT  *
FROM SALES.PRODUCTS 
WHERE PRICE BETWEEN 100000 AND 200000 


--(EXEMPLO 2) USO DO COMANDO NOT 
-- SELEICONE VEICULOS QUE CUSTAM ABAIXO DE 100K OU ACIMA DE 200K

SELECT *
FROM SALES.PRODUCTS
WHERE PRICE < 100000 OR PRICE > 200000 


SELECT *
FROM SALES.PRODUCTS
WHERE PRICE NOT BETWEEN 100000 AND 200000

-- (EXEMPLO 3) USO DO COMANDO IN
-- SELECIONAR PRODUTOS QUE SEJAM DA MARCA HONDA, TOYOTA OU RENAULT


SELECT *
FROM SALES.PRODUCTS 
WHERE BRAND = 'HONDA' OR  BRAND = 'TOYOTA' OR BRAND = 'RENAULT'

SELECT *
FROM SALES.PRODUCTS 
WHERE BRAND IN ('HONDA', 'TOYPTA', 'RENAULT')

SELECT *
FROM SALES.PRODUCTS 
WHERE BRAND  NOT IN ('HONDA', 'TOYPTA', 'RENAULT')

--(EXEMPLO 4) USO DO COMANDO LIKE (MATCHS IMPERFEITOS)
-- SELECIONE OS PRIMEIROS NOMES DISTINTOS A TABELA CUSTOMERS QUE COMEÇAM 
--COM AS INICIAIS ANA 

SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME = 'ANA'


SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME LIKE 'ANA%'


SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME LIKE '%ANA'

--(EXEMPLO 5) USO DO COMANDO ILIKE (IGNORA LETRAS MAIÚSCULAS E MINÚSCULAS)
--SELECIONE OS PRIMEIROS NOMES DISTINTOS COM INICIAIS 'ANA'
SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME LIKE 'ANA%'

SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME ILIKE 'ana%'

--(EXEMPLO 6) USO DO COMANDO IS NULL 
--SELECIONAR APENAS AS LINHAS QUE CONTEM NULO NO CAMPO "POPULATION" NA TABELA 
--TEMP_TABLES.REGIONS

SELECT *
FROM TEMP_TABLES.REGIONS

SELECT *
FROM TEMP_TABLES.REGIONS
WHERE POPULATION IS NULL
