-- ORDER BY 
-- SERVE PARA ORDENAR  A SELACAO  DE ACORDO COM UMA REGRA DEFINIDA PELO USUARIO 

-- SIXTAXE 

SELECT COLUNA_1, COLUNA_2, COLUNA_3
FROM SCHEMA_1.TABELA_1
WHERE CONDICAO_X=TRUE
ORDER BY COLUNA_1

-- (EXEMPLO 1 ) ORDENACAO DE VALORES NUMERICOS 
-- LISTE PRODUTOS DA TABELA PRODUCTS NA ORDEM CRESCENTE COM BASE NO PREÇO 

SELECT *
FROM SALES.PRODUCTS 
ORDER BY price desc

--(EXEMPRO 2) ORDENACAO DE TEXTO
--LISTE OS ESTADOS DISTINTOS DA TABELA CUSTOMERS NA ORDEM CRESCENTE 

SELECT DISTINCT STATE
FROM sales.customers 
order by state