-- (EXEMPRO 1)  SELEÇÃO DE  UMA COLUNA DE UMA TABELA 
-- LISTE OS E-MAILS DOS CLIENTES  DA TABELA SALES.CUSTOMERS 

select email
from sales.customers

-- (EXEMPRO 2) SELEÇÃO DE MAIS DE UMA  COLUNA DE UMA TABELA 
-- LISTE O EMAILS  E NOMES DOS CLIENTES  DA TABELA SALES.CUSTOMERS

select email, first_name, last_name
from sales.customers



-- (EXEMPLO) SELEÇÃO DE TODAS AS COLUNAS  DE UMA TABELA 
-- LISTE TODAS AS INFOMAÇOES DOS CLIENTES  DA TABELA SALES.CUSTOMERS

select * 
from sales.customers
