-- (WHERE) SERVE PARA FILTRAR AS LINHAS DA TABELA DE ACORDO COM UMA CONDIÇÃO 

SELECT COLUNA_1, COLUNA_2, COLUNA3
FROM SCHEMA_1.TABELA_1
WHERE CONDICAO_X=true



--(EXEMPLO 1) FILTRO COM CONDICAO UNICA 
-- LISTE OS EMAILS DOS CLIENTES DA NOSSA BASE QUE MORAM NO ESTADO DE SANTA CATARINA 

SELECT EMAIL, STATE 
FROM SALES.CUSTOMERS
WHERE STATE = 'SC'

-- (EXEMPLO 2)  FILTRO COM MAIS DE UMA CONDICAO 
-- LISTE OS EMAILS DOS CLIENTES DA NOSSA BASE QUE MORAM NO ESTADO DE SANTA CATRINA 
--OU MATO GROSSO DO SUL 

SELECT EMAIL, STATE 
FROM SALES.CUSTOMERS
WHERE STATE = 'SC'  OR STATE = 'MS'


--(EXEMPLO 3) FILTRO DE CONDICAO COM DATA
--LISTE OS EMAILS DOS CLIENTES DA NOSSA BASE QUE MORAM NO ESTADO DE SANTA CATARINA 
-- OU MATO GROSSO DO SUL E QUE TEM MAIS DE 30 ANOS


SELECT EMAIL, STATE, birth_date
FROM SALES.CUSTOMERS
WHERE (STATE = 'SC' OR STATE = 'MS') AND birth_date < '1991-12-28'
